### PR TITLE
Downloading Git Supermacy

### PR DESCRIPTION
**Pull request by ArezalGame89**
Downloads Git after user has inputted that they do NOT own GitHub CLI or Git's MINGW-64

### CODE REVIEW

**Comment by Iemane291** [comment]
I won't accept this PR because I think it's a little insecure to use the webbrowser module. We could just tell the user to install it tho.

**Comment by Iemane291** [comment]
And downloading Git automatically for them is just no. Just let them do it manually. Give them a choice damn

**Comment by ArezalGame89** [comment]
> And downloading Git automatically for them is just no. Just let them do it manually. Give them a choice damn

Ok + It wasn't automatic download + could make this setting called "autodownloading".

**Comment by Iemane291** [comment]
thats the new ratio + fatherless + who asked

**Pull request closed without merging**
